In [16]:
import numpy as np
import tensorflow as tf
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D
from keras.layers import Conv2DTranspose
# define input data
X = asarray([[1, 2],
			 [3, 4]])
# show input data for context
print(X)
# reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))
# define model
model = Sequential()
model.add(UpSampling2D(size=(3,3),input_shape=(2, 2, 1)))
# summarize the model
model.summary()
# make a prediction with the model
yhat = model.predict(X)
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((6, 6))
# summarize output
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_5 (UpSampling2 (None, 6, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]]


In [2]:
model.weights

[]

In [3]:
# define input data
X = asarray([[1, 2, 6],
			 [3, 4, 6]])
# show input data for context
print(X)
# reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 3, 1))
# define model
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 3, 1)))
# summarize the model
model.summary()
# make a prediction with the model
yhat = model.predict(X)
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 6))
# summarize output
print(yhat)

[[1 2 6]
 [3 4 6]]
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1. 2. 2. 6. 6.]
 [1. 1. 2. 2. 6. 6.]
 [3. 3. 4. 4. 6. 6.]
 [3. 3. 4. 4. 6. 6.]]


In [12]:
a = np.array([[0,0, 0,0],
              [0,2, 4,0],
              [0,0, 1,0],
              [0,0, 0,0]]).reshape(1,4,4,1)

filt = np.array([[3, 1],
                 [1, 5.0]]).reshape(2,2,1,1)

b = tf.nn.conv2d_transpose(a,
                           filt,
                           output_shape=[1,4,4,1],
                           strides=[1,1,1,1],
                           padding='SAME')

print(tf.squeeze(b))

tf.Tensor(
[[ 0.  0.  0.  0.]
 [ 0.  6. 14.  4.]
 [ 0.  2. 17. 21.]
 [ 0.  0.  1.  5.]], shape=(4, 4), dtype=float64)


In [5]:
model2 = Sequential()
model2.add(Conv2DTranspose(filters=1, kernel_size=(2,2),input_shape=(2, 3, 1)))

In [6]:
model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 3, 4, 1)           5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [7]:
yhat = model2.predict(X)

In [9]:
yhat.shape

(1, 3, 4, 1)

In [10]:
yhat

array([[[[-2.7378798e-03],
         [ 3.0160874e-01],
         [ 5.9774172e-01],
         [ 1.8425070e+00]],

        [[ 4.7563022e-01],
         [ 1.6648579e+00],
         [ 3.6887102e+00],
         [ 5.6371558e-01]],

        [[ 1.4515316e+00],
         [ 1.2959797e+00],
         [ 2.0505357e+00],
         [-1.2787914e+00]]]], dtype=float32)